import GetAllAutoInstructionSuggestionUseCase
    from "./GetAllAutoInstructionSuggestion/GetAllAutoInstructionSuggestionUseCase";
import GetAutoInstructionSuggestionUseCase from "./GetAutoInstructionSuggestion/GetAutoInstructionSuggestionUseCase";

export type AvailableAutoInstructionSuggestionUseCases =
	| GetAllAutoInstructionSuggestionUseCase
	| GetAutoInstructionSuggestionUseCase;