services:
  mysql:
    image: mysql:8.4
    restart: on-failure
    container_name: hdm-mwc-api
    environment:
      - APP_ENV=${APP_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - API_PORT=${API_PORT}
      - WORKERS_PORT=${WORKERS_PORT}
      - GRAPHQL_PLAYGROUND_ENABLED=${GRAPHQL_PLAYGROUND_ENABLED}
      - DATABASE_URL=${DATABASE_URL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - CDN_ACCESS_KEY_ID=${CDN_ACCESS_KEY_ID}
      - CDN_ACCESS_KEY=${CDN_ACCESS_KEY}
      - CDN_PUBLIC_URL=${CDN_PUBLIC_URL}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
      - JWT_SECRET_TIO=${JWT_SECRET_TIO}
      - TIO_URL_GRAPHQL=${TIO_URL_GRAPHQL}
      - POSTMARK_SERVER_TOKEN=${POSTMARK_SERVER_TOKEN}
      - POSTMARK_SERVER_PORT=${POSTMARK_SERVER_PORT}
      - POSTMARK_MESSAGE_STREAM=${POSTMARK_MESSAGE_STREAM}
      - MAIL_SENDER=${MAIL_SENDER}
      - FRONTEND_URL=${FRONTEND_URL}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql:
